### PR TITLE
Ripkens is dead, long live Saltychat-AltV

### PR DESCRIPTION
**Pull request by vesturo**
yeah i wrote abt that in discord already

### CODE REVIEW

**Comment by BlackFlash5** [comment]
Declaring someone as dead isn't really a nice way to say that the repo isn't properly maintained.
What does your repo offer that his doesn't? I couldn't see an implementation of distance culling, which his for example lacks.

**Comment by vesturo** [comment]
> Declaring someone as dead isn't really a nice way to say that the repo isn't properly maintained.
> What does your repo offer that his doesn't? I couldn't see an implementation of distance culling, which his for example lacks.

at the moment it's on the same stage as his but with updated readme and me having the time of helping people with their salty problems as i figured out most stuff by now. 

I'm already working on some things like as an example an easy way to stop people from playing without saltychat. it's planned to be a general rework of the whole script basically.

**Comment by BlackFlash5** [comment]
One thing you should do is update the supported versions.
Every version within a major version is compatible with each other. So if you have a script that works with any 2.x.x version, it will work for all 2.x.x versions.
https://github.com/saltminede/saltychat-docs#versioning-and-update-branches

**Comment by vesturo** [comment]
> One thing you should do is update the supported versions.
> Every version within a major version is compatible with each other. So if you have a script that works with any 2.x.x version, it will work for all 2.x.x versions.
> https://github.com/saltminede/saltychat-docs#versioning-and-update-branches

Will do :)

**Pull request merged**
